apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: idpflow
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          # Image tag is updated by CI pipeline after each build
          image: idpflowacr1.azurecr.io/backend:43
          ports:
            - containerPort: 7860
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 7860
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7860
            initialDelaySeconds: 30
            periodSeconds: 30
