import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Download, Loader2, X, Image as ImageIcon } from "lucide-react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";
import { BASE_URL_API } from "@/constants/constants";

export default function OrchestratorImageGallery() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [selectedImage, setSelectedImage] = useState<{
    src: string;
    name: string;
  } | null>(null);
  const [images, setImages] = useState<{ id: string; name: string; src: string; createdAt: string }[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Fetch AI-generated images from dedicated MiBuddy endpoint
  useEffect(() => {
    const tokenMatch = document.cookie.match(/(?:^|;\s*)access_token_ag=([^;]*)/);
    const headers: Record<string, string> = {};
    if (tokenMatch?.[1]) headers["Authorization"] = `Bearer ${decodeURIComponent(tokenMatch[1])}`;

    fetch(`${BASE_URL_API}orchestrator/generated-images`, { headers, credentials: "include" })
      .then((res) => res.json())
      .then((data: any[]) => {
        setImages(
          (data || []).map((img: any, idx: number) => ({
            id: `gen-${idx}`,
            name: img.name || "AI Generated Image",
            src: img.src,
            createdAt: "",
          })),
        );
      })
      .catch((err) => console.warn("Failed to load generated images:", err))
      .finally(() => setIsLoading(false));
  }, []);

  const handleDownload = useCallback(
    async (src: string, name: string) => {
      try {
        const res = await fetch(src);
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = name || `image-${Date.now()}.png`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      } catch {
        // fallback: open in new tab
        window.open(src, "_blank");
      }
    },
    [],
  );

  return (
    <div className="flex h-full w-full flex-col bg-background">
      {/* ── Header ── */}
      <div className="flex items-center gap-4 border-b border-border px-6 py-4">
        <button
          onClick={() => navigate("/orchestrator-chat")}
          className="rounded-lg p-2 text-muted-foreground hover:bg-accent hover:text-foreground"
        >
          <ArrowLeft size={20} />
        </button>
        <div className="flex items-center gap-2.5">
          <ImageIcon size={22} className="text-primary" />
          <h1 className="text-xl font-semibold text-foreground">
            {t("My Images")}
          </h1>
        </div>
        <span className="ml-auto text-sm text-muted-foreground">
          {images.length > 0
            ? `${t("Showing")} ${images.length} ${t("most recent")}`
            : ""}
        </span>
      </div>

      {/* ── Body ── */}
      <div className="flex-1 overflow-y-auto p-6">
        {isLoading ? (
          <div className="flex h-64 items-center justify-center">
            <Loader2 size={32} className="animate-spin text-muted-foreground" />
          </div>
        ) : images.length === 0 ? (
          <div className="flex h-64 flex-col items-center justify-center gap-3 text-muted-foreground">
            <ImageIcon size={48} className="opacity-30" />
            <p className="text-lg">{t("No images available")}</p>
            <p className="text-sm">
              {t("Images generated by agents will appear here")}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
            {images.map((img) => (
              <div
                key={img.id}
                className="group relative cursor-pointer overflow-hidden rounded-xl border border-border bg-muted/30 transition-shadow hover:shadow-lg hover:border-primary/50"
                onClick={() => setSelectedImage({ src: img.src, name: img.name })}
              >
                {/* Image */}
                <div className="aspect-square overflow-hidden">
                  <img
                    src={img.src}
                    alt={img.name}
                    className="h-full w-full object-cover transition-transform group-hover:scale-105"
                    loading="lazy"
                  />
                </div>

                {/* Overlay with actions */}
                <div className="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 transition-opacity group-hover:opacity-100">
                  <div className="flex items-center justify-between p-3">
                    <span className="max-w-[70%] truncate text-xs font-medium text-white">
                      {img.name}
                    </span>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDownload(img.src, img.name);
                      }}
                      className="rounded-full bg-white/20 p-1.5 text-white backdrop-blur-sm hover:bg-white/40"
                      title={t("Download")}
                    >
                      <Download size={14} />
                    </button>
                  </div>
                </div>

                {/* Date badge */}
                {img.createdAt && (
                  <div className="absolute right-2 top-2 rounded-md bg-black/40 px-1.5 py-0.5 text-xxs text-white opacity-0 backdrop-blur-sm group-hover:opacity-100">
                    {new Date(img.createdAt).toLocaleDateString()}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ── Lightbox modal ── */}
      {selectedImage && (
        <div
          className="fixed inset-0 z-[300] flex items-center justify-center bg-black/80"
          onClick={() => setSelectedImage(null)}
        >
          <div
            className="relative flex max-h-[90vh] max-w-[90vw] flex-col items-center"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setSelectedImage(null)}
              className="absolute -right-3 -top-3 z-10 rounded-full bg-zinc-800 p-2 text-white shadow-lg hover:bg-zinc-700"
            >
              <X size={18} />
            </button>
            <img
              src={selectedImage.src}
              alt={selectedImage.name}
              className="max-h-[80vh] max-w-[85vw] rounded-lg object-contain"
            />
            <div className="mt-4 flex items-center gap-4">
              <span className="max-w-xs truncate text-sm text-white/80">
                {selectedImage.name}
              </span>
              <button
                onClick={() =>
                  handleDownload(selectedImage.src, selectedImage.name)
                }
                className="flex items-center gap-2 rounded-lg bg-white/10 px-4 py-2 text-sm text-white backdrop-blur-sm hover:bg-white/20"
              >
                <Download size={16} />
                {t("Download")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
