#!/bin/sh
set -eu

cat > /usr/share/nginx/html/config.js <<EOF
window.__APP_CONFIG__ = {
  BACKEND_URL: "${BACKEND_URL:-}",
  VITE_API_URL: "${VITE_API_URL:-}",
  VITE_PROXY_TARGET: "${VITE_PROXY_TARGET:-}",
  HOST_IP: "${HOST_IP:-}",
  BACKEND_PORT: "${BACKEND_PORT:-}",
  FRONTEND_PORT: "${FRONTEND_PORT:-}",
  LOCALHOST_HOST: "${LOCALHOST_HOST:-}",
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID:-}",
  AZURE_TENANT_ID: "${AZURE_TENANT_ID:-}",
  AZURE_REDIRECT_URI: "${AZURE_REDIRECT_URI:-}",
  MSAL_AUTHORITY: "${MSAL_AUTHORITY:-}",
  MSAL_REDIRECT_URI: "${MSAL_REDIRECT_URI:-}",
  MSAL_POST_LOGOUT_REDIRECT_URI: "${MSAL_POST_LOGOUT_REDIRECT_URI:-}",
};
EOF
