"""rename_match_indexes

Revision ID: 66820c73143d
Revises: idp_g3_dedup_unique_idx
Create Date: 2026-07-01 18:31:10.368946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from agentcore.utils import migration


# revision identifiers, used by Alembic.
revision: str = '66820c73143d'
down_revision: Union[str, None] = 'idp_g3_dedup_unique_idx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idp_agent_match_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_idp_agent_match_configs_agent_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_idp_agent_match_configs_agent_id'))
        batch_op.create_index(batch_op.f('ix_idp_agent_match_configs_agent_id'), ['agent_id'], unique=True)

    with op.batch_alter_table('idp_match_discrepancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_match_discrepancies_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_match_discrepancies_match_result_id'), ['match_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idp_match_discrepancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_match_discrepancies_match_result_id'))
        batch_op.drop_index(batch_op.f('ix_idp_match_discrepancies_document_id'))

    with op.batch_alter_table('idp_agent_match_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_agent_match_configs_agent_id'))
        batch_op.create_index(batch_op.f('ix_idp_agent_match_configs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_idp_agent_match_configs_agent_id'), ['agent_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
