"""add session_title to orch_conversation

Revision ID: 95791a21c989
Revises: s1h2o3w4i5n6
Create Date: 2026-04-16 14:39:09.561201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from agentcore.utils import migration


# revision identifiers, used by Alembic.
revision: str = '95791a21c989'
down_revision: Union[str, None] = 's1h2o3w4i5n6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orch_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orch_conversation', schema=None) as batch_op:
        batch_op.drop_column('session_title')

    # ### end Alembic commands ###
