"""create_package_table

Revision ID: a7b8c9d0e1f2
Revises: 32241ba468df
Create Date: 2026-02-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from agentcore.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'a7b8c9d0e1f2'
down_revision: Union[str, None] = '32241ba468df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('version_spec', sa.String(length=255), nullable=True),
    sa.Column('package_type', sa.String(length=20), nullable=False),
    sa.Column('required_by', sa.JSON(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'package_type', name='uq_package_name_type')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_package_type'), ['package_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_package_type'))
        batch_op.drop_index(batch_op.f('ix_package_name'))

    op.drop_table('package')
    # ### end Alembic commands ###
