"""create_teams_app_table

Revision ID: b9f48ef919cd
Revises: l9a0b1c2d3e4
Create Date: 2026-02-20 02:19:31.146278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from agentcore.utils import migration
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9f48ef919cd'
down_revision: Union[str, None] = 'l9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_app',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('teams_app_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manifest_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UPLOADED', 'PUBLISHED', 'FAILED', 'UNPUBLISHED', name='teams_publish_status_enum'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('manifest_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams_app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_app_agent_id'), ['agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_app_agent_id'))

    op.drop_table('teams_app')
    # ### end Alembic commands ###
