"""Autogenerate schema diffs

Revision ID: e43f32eb5cb1
Revises: z9y8x7w6v5u4
Create Date: 2026-02-27 00:49:53.650505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from agentcore.utils import migration
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43f32eb5cb1'
down_revision: Union[str, None] = 'z9y8x7w6v5u4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    kb_visibility_enum = postgresql.ENUM("PRIVATE", "DEPARTMENT", "ORGANIZATION", name="kb_visibility_enum")
    kb_visibility_enum.create(conn, checkfirst=True)
    teams_publish_status_enum = postgresql.ENUM(
        "DRAFT",
        "UPLOADED",
        "PUBLISHED",
        "FAILED",
        "UNPUBLISHED",
        name="teams_publish_status_enum",
        create_type=False,
    )
    teams_publish_status_enum.create(conn, checkfirst=True)

    inspector = sa.inspect(conn)

    def _table_exists(table_name: str) -> bool:
        return table_name in inspector.get_table_names()

    def _column_exists(table_name: str, column_name: str) -> bool:
        if not _table_exists(table_name):
            return False
        return any(col["name"] == column_name for col in inspector.get_columns(table_name))

    def _index_exists(table_name: str, index_name: str) -> bool:
        if not _table_exists(table_name):
            return False
        return any(idx["name"] == index_name for idx in inspector.get_indexes(table_name))

    if not _table_exists('agent_edit_lock'):
        op.create_table('agent_edit_lock',
        sa.Column('agent_id', sa.Uuid(), nullable=False),
        sa.Column('locked_by', sa.Uuid(), nullable=False),
        sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
        sa.ForeignKeyConstraint(['locked_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('agent_id')
        )
    if _table_exists('agent_edit_lock'):
        with op.batch_alter_table('agent_edit_lock', schema=None) as batch_op:
            if not _index_exists('agent_edit_lock', batch_op.f('ix_agent_edit_lock_expires_at')):
                batch_op.create_index(batch_op.f('ix_agent_edit_lock_expires_at'), ['expires_at'], unique=False)
            if not _index_exists('agent_edit_lock', batch_op.f('ix_agent_edit_lock_locked_by')):
                batch_op.create_index(batch_op.f('ix_agent_edit_lock_locked_by'), ['locked_by'], unique=False)

    if not _table_exists('teams_app'):
        op.create_table('teams_app',
        sa.Column('agent_id', sa.Uuid(), nullable=False),
        sa.Column('teams_app_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('bot_app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('bot_app_secret', sa.Text(), nullable=True),
        sa.Column('manifest_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('short_description', sa.Text(), nullable=True),
        sa.Column('status', teams_publish_status_enum, server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column('published_by', sa.Uuid(), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('manifest_data', sa.JSON(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
        sa.ForeignKeyConstraint(['published_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if _table_exists('teams_app'):
        with op.batch_alter_table('teams_app', schema=None) as batch_op:
            if not _index_exists('teams_app', batch_op.f('ix_teams_app_agent_id')):
                batch_op.create_index(batch_op.f('ix_teams_app_agent_id'), ['agent_id'], unique=False)

    if _table_exists('agent'):
        with op.batch_alter_table('agent', schema=None) as batch_op:
            if _column_exists('agent', 'action_description'):
                batch_op.drop_column('action_description')
            if _column_exists('agent', 'action_name'):
                batch_op.drop_column('action_name')
            if _column_exists('agent', 'mcp_enabled'):
                batch_op.drop_column('mcp_enabled')
    if _table_exists('guardrail_catalogue'):
        with op.batch_alter_table('guardrail_catalogue', schema=None) as batch_op:
            if _index_exists('guardrail_catalogue', batch_op.f('ix_guardrail_catalogue_model_registry_id')):
                batch_op.drop_index(batch_op.f('ix_guardrail_catalogue_model_registry_id'))
            for fk in inspector.get_foreign_keys('guardrail_catalogue'):
                if fk.get('name') == batch_op.f('fk_guardrail_catalogue_model_registry_id_model_registry'):
                    batch_op.drop_constraint(batch_op.f('fk_guardrail_catalogue_model_registry_id_model_registry'), type_='foreignkey')
                    break
            if _column_exists('guardrail_catalogue', 'model_registry_id'):
                batch_op.drop_column('model_registry_id')
    if _table_exists('knowledge_base') and not _column_exists('knowledge_base', 'visibility'):
        with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
            batch_op.add_column(sa.Column('visibility', sa.Enum('PRIVATE', 'DEPARTMENT', 'ORGANIZATION', name='kb_visibility_enum'), server_default=sa.text("'PRIVATE'"), nullable=False))
            if not _index_exists('knowledge_base', 'ix_knowledge_base_visibility'):
                batch_op.create_index('ix_knowledge_base_visibility', ['visibility'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_base_visibility')
        batch_op.drop_column('visibility')

    kb_visibility_enum = postgresql.ENUM("PRIVATE", "DEPARTMENT", "ORGANIZATION", name="kb_visibility_enum")
    kb_visibility_enum.drop(conn, checkfirst=True)

    with op.batch_alter_table('guardrail_catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_registry_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_guardrail_catalogue_model_registry_id_model_registry'), 'model_registry', ['model_registry_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_guardrail_catalogue_model_registry_id'), ['model_registry_id'], unique=False)

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('teams_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_app_agent_id'))

    op.drop_table('teams_app')
    with op.batch_alter_table('agent_edit_lock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_edit_lock_locked_by'))
        batch_op.drop_index(batch_op.f('ix_agent_edit_lock_expires_at'))

    op.drop_table('agent_edit_lock')
    # ### end Alembic commands ###
