"""add idp tables

Revision ID: ef20f6472bed
Revises: e7a90c09c765
Create Date: 2026-06-04 13:22:25.296571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from agentcore.utils import migration
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef20f6472bed'
down_revision: Union[str, None] = 'e7a90c09c765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idp_field_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_idp_field_config_org_name')
    )
    with op.batch_alter_table('idp_field_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_field_configurations_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_field_configurations_org_id'), ['org_id'], unique=False)

    op.create_table('idp_field_config_headers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("field_type IN ('text','number','date','boolean')", name='ck_idp_cfg_header_type'),
    sa.ForeignKeyConstraint(['config_id'], ['idp_field_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'field_name', name='uq_idp_cfg_header_config_field')
    )
    with op.batch_alter_table('idp_field_config_headers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_field_config_headers_config_id'), ['config_id'], unique=False)

    op.create_table('idp_field_config_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('column_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("column_type IN ('text','number','date')", name='ck_idp_cfg_line_type'),
    sa.ForeignKeyConstraint(['config_id'], ['idp_field_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'column_name', name='uq_idp_cfg_line_config_col')
    )
    with op.batch_alter_table('idp_field_config_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_field_config_line_items_config_id'), ['config_id'], unique=False)

    op.create_table('idp_agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_mode', sa.String(length=30), nullable=False),
    sa.Column('field_config_id', sa.Uuid(), nullable=True),
    sa.Column('dynamic_prompt', sa.Text(), nullable=True),
    sa.Column('preprocessing_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('multi_doc_split', sa.Boolean(), nullable=False),
    sa.Column('default_rule_action', sa.String(length=20), nullable=False),
    sa.Column('auto_stop_after_batch', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("default_rule_action IN ('auto_approve','pending_review')", name='ck_idp_agents_default_action'),
    sa.CheckConstraint("extraction_mode IN ('dynamic_prompting','named_config','multimodal')", name='ck_idp_agents_mode'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_config_id'], ['idp_field_configurations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_agents_agent_id'), ['agent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_idp_agents_field_config_id'), ['field_config_id'], unique=False)

    op.create_table('idp_agent_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idp_agent_id', sa.Uuid(), nullable=False),
    sa.Column('rule_group', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('field_b', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('combinator', sa.String(length=3), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('auto_approve','pending_review')", name='ck_idp_rules_action'),
    sa.CheckConstraint("combinator IN ('AND','OR')", name='ck_idp_rules_combinator'),
    sa.CheckConstraint("condition_type IN ('confidence_overall','confidence_field','field_value_numeric','field_value_text','field_value_date','field_comparison','field_presence','pattern_regex','visual_element')", name='ck_idp_rules_condition_type'),
    sa.ForeignKeyConstraint(['idp_agent_id'], ['idp_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_agent_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_agent_rules_idp_agent_id'), ['idp_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_agent_rules_rule_group'), ['rule_group'], unique=False)
        batch_op.create_index('ix_idp_rules_agent_group_order', ['idp_agent_id', 'rule_group', 'display_order'], unique=False)

    op.create_table('idp_bulk_processing_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.String(length=10), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('failed_documents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','completed','partial','failed','cancelled')", name='ck_idp_batch_status'),
    sa.CheckConstraint("trigger_type IN ('auto','manual')", name='ck_idp_batch_trigger'),
    sa.ForeignKeyConstraint(['agent_id'], ['idp_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_catalogue.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_bulk_processing_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_bulk_processing_batches_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_bulk_processing_batches_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_bulk_processing_batches_status'), ['status'], unique=False)

    op.create_table('idp_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('parent_document_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('upload','mail_connector','sharepoint','other')", name='ck_idp_documents_source'),
    sa.CheckConstraint("status IN ('queued','processing','extracted','pending_review','auto_approved','reviewed','failed')", name='ck_idp_documents_status'),
    sa.CheckConstraint('overall_confidence IS NULL OR (overall_confidence >= 0 AND overall_confidence <= 1)', name='ck_idp_documents_conf'),
    sa.ForeignKeyConstraint(['agent_id'], ['idp_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_catalogue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_document_id'], ['idp_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_documents_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_idp_documents_agent_status_created', ['agent_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_documents_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_documents_parent_document_id'), ['parent_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_documents_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('idp_detected_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('element_type', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('decoded_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_idp_detected_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_detected_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_detected_elements_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_detected_elements_element_type'), ['element_type'], unique=False)

    op.create_table('idp_document_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['idp_bulk_processing_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'document_id', name='uq_idp_doc_batch_batch_doc')
    )
    with op.batch_alter_table('idp_document_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_document_batches_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_document_batches_document_id'), ['document_id'], unique=False)

    op.create_table('idp_document_classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_config_id', sa.Uuid(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_idp_classification_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_config_id'], ['idp_field_configurations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_document_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_document_classifications_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_document_classifications_predicted_type'), ['predicted_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_document_classifications_selected_config_id'), ['selected_config_id'], unique=False)

    op.create_table('idp_document_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_section_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['idp_document_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_document_sections_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_document_sections_parent_section_id'), ['parent_section_id'], unique=False)

    op.create_table('idp_entity_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('entity_key', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('occurrences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_entity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_entity_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_entity_links_entity_key'), ['entity_key'], unique=False)

    op.create_table('idp_processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_mode_used', sa.String(length=30), nullable=True),
    sa.Column('math_reconcile_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','completed','failed')", name='ck_idp_jobs_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['idp_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_idp_jobs_agent_status_created', ['agent_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_idp_jobs_document_created', ['document_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_processing_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_processing_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_processing_jobs_status'), ['status'], unique=False)

    op.create_table('idp_review_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=False),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("final_status IS NULL OR final_status IN ('approved','corrections_made')", name='ck_idp_review_final_status'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idp_review_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_idp_review_doc_completed', ['document_id', 'review_completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_review_sessions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_review_sessions_reviewed_by'), ['reviewed_by'], unique=False)

    op.create_table('idp_extracted_headers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('source_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_value', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_idp_ext_header_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['idp_processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'field_name', name='uq_idp_ext_header_job_field')
    )
    with op.batch_alter_table('idp_extracted_headers', schema=None) as batch_op:
        batch_op.create_index('ix_idp_ext_header_doc_field', ['document_id', 'field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_extracted_headers_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_extracted_headers_job_id'), ['job_id'], unique=False)

    op.create_table('idp_extracted_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('source_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_value', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_idp_ext_line_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['idp_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['idp_processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'row_index', 'column_name', name='uq_idp_ext_line_job_row_col')
    )
    with op.batch_alter_table('idp_extracted_line_items', schema=None) as batch_op:
        batch_op.create_index('ix_idp_ext_line_doc_row', ['document_id', 'row_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_extracted_line_items_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idp_extracted_line_items_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idp_extracted_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_extracted_line_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_idp_extracted_line_items_document_id'))
        batch_op.drop_index('ix_idp_ext_line_doc_row')

    op.drop_table('idp_extracted_line_items')
    with op.batch_alter_table('idp_extracted_headers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_extracted_headers_job_id'))
        batch_op.drop_index(batch_op.f('ix_idp_extracted_headers_document_id'))
        batch_op.drop_index('ix_idp_ext_header_doc_field')

    op.drop_table('idp_extracted_headers')
    with op.batch_alter_table('idp_review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_review_sessions_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_idp_review_sessions_document_id'))
        batch_op.drop_index('ix_idp_review_doc_completed')

    op.drop_table('idp_review_sessions')
    with op.batch_alter_table('idp_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_idp_processing_jobs_document_id'))
        batch_op.drop_index(batch_op.f('ix_idp_processing_jobs_agent_id'))
        batch_op.drop_index('ix_idp_jobs_document_created')
        batch_op.drop_index('ix_idp_jobs_agent_status_created')

    op.drop_table('idp_processing_jobs')
    with op.batch_alter_table('idp_entity_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_entity_links_entity_key'))
        batch_op.drop_index(batch_op.f('ix_idp_entity_links_document_id'))

    op.drop_table('idp_entity_links')
    with op.batch_alter_table('idp_document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_document_sections_parent_section_id'))
        batch_op.drop_index(batch_op.f('ix_idp_document_sections_document_id'))

    op.drop_table('idp_document_sections')
    with op.batch_alter_table('idp_document_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_document_classifications_selected_config_id'))
        batch_op.drop_index(batch_op.f('ix_idp_document_classifications_predicted_type'))
        batch_op.drop_index(batch_op.f('ix_idp_document_classifications_document_id'))

    op.drop_table('idp_document_classifications')
    with op.batch_alter_table('idp_document_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_document_batches_document_id'))
        batch_op.drop_index(batch_op.f('ix_idp_document_batches_batch_id'))

    op.drop_table('idp_document_batches')
    with op.batch_alter_table('idp_detected_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_detected_elements_element_type'))
        batch_op.drop_index(batch_op.f('ix_idp_detected_elements_document_id'))

    op.drop_table('idp_detected_elements')
    with op.batch_alter_table('idp_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_documents_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_idp_documents_status'))
        batch_op.drop_index(batch_op.f('ix_idp_documents_parent_document_id'))
        batch_op.drop_index(batch_op.f('ix_idp_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_idp_documents_connector_id'))
        batch_op.drop_index('ix_idp_documents_agent_status_created')
        batch_op.drop_index(batch_op.f('ix_idp_documents_agent_id'))

    op.drop_table('idp_documents')
    with op.batch_alter_table('idp_bulk_processing_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_bulk_processing_batches_status'))
        batch_op.drop_index(batch_op.f('ix_idp_bulk_processing_batches_connector_id'))
        batch_op.drop_index(batch_op.f('ix_idp_bulk_processing_batches_agent_id'))

    op.drop_table('idp_bulk_processing_batches')
    with op.batch_alter_table('idp_agent_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_idp_rules_agent_group_order')
        batch_op.drop_index(batch_op.f('ix_idp_agent_rules_rule_group'))
        batch_op.drop_index(batch_op.f('ix_idp_agent_rules_idp_agent_id'))

    op.drop_table('idp_agent_rules')
    with op.batch_alter_table('idp_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_agents_field_config_id'))
        batch_op.drop_index(batch_op.f('ix_idp_agents_agent_id'))

    op.drop_table('idp_agents')
    with op.batch_alter_table('idp_field_config_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_field_config_line_items_config_id'))

    op.drop_table('idp_field_config_line_items')
    with op.batch_alter_table('idp_field_config_headers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_field_config_headers_config_id'))

    op.drop_table('idp_field_config_headers')
    with op.batch_alter_table('idp_field_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_field_configurations_org_id'))
        batch_op.drop_index(batch_op.f('ix_idp_field_configurations_created_by'))

    op.drop_table('idp_field_configurations')
    # ### end Alembic commands ###
